---
label: Config file
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: tagline
  label: tagline
- type: text
  name: email
  label: email
- type: textarea
  name: description
  label: description
- type: text
  name: url
  label: url
- type: text
  name: logo
  label: logo
- type: text
  name: logo_square
  label: logo_square
- type: text
  name: logo_light
  label: logo_light
- type: text
  name: facebook
  label: facebook
- type: text
  name: twitter
  label: twitter
- type: text
  name: instagram
  label: instagram
- type: text
  name: copyright_notice
  label: copyright_notice
- type: text
  name: donate
  label: donate
- type: text
  name: join_us
  label: join_us
- type: text
  name: brand_color
  label: brand_color
- type: text
  name: accent_color
  label: accent_color
- type: boolean
  name: invert_brand_text
  label: invert_brand_text
- type: boolean
  name: invert_accent_text
  label: invert_accent_text
- type: text
  name: baseurl
  label: baseurl
- type: text
  name: permalink
  label: permalink
- type: text
  name: locale
  label: locale
- type: text
  name: theme
  label: theme
- type: list
  name: plugins
  label: plugins
- type: field_group
  name: csv
  label: csv
  fields:
  - type: field_group
    name: rebels
    label: rebels
    fields:
    - type: textarea
      name: source
      label: source
- type: field_group
  name: collections
  label: collections
  fields:
  - type: field_group
    name: rebels
    label: rebels
    fields:
    - type: boolean
      name: output
      label: output
  - type: field_group
    name: posts
    label: posts
    fields:
    - type: text
      name: permalink
      label: permalink
- type: number
  name: theme_tiny
  label: theme_tiny
- type: number
  name: theme_small
  label: theme_small
- type: number
  name: theme_medium
  label: theme_medium
- type: number
  name: theme_large
  label: theme_large
- type: list
  name: exclude
  label: exclude
